development:
  fedora:
    url: https://hydra:h4drang3a@repository2.cul.columbia.edu:8443/fedora
  solr:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/hydrangea
test:
  fedora:
    url: https://hydra:h4drang3a@repository2.cul.columbia.edu:8443/fedora
  solr:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/hydrangea
