development:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/hydrangea
test: &TEST
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/hydrangea
passenger_dev:
    url: http://testcat.cul.columbia.edu:8983/solr-1.5/hydrangea
passenger_test:
    url: http://katana.cul.columbia.edu:8080/solr-1.5/scv_test
passenger_prod:
    url: http://macana.cul.columbia.edu:8080/solr-1.5/scv_prod
cucumber:
    <<: *TEST
